name: 'exam_dbt'
version: '1.0.0'
config-version: 2

profile: 'exam_dbt'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  exam_dbt:
    staging:
      +materialized: view

    star:
      +materialized: table
      +tags: ["star_schema"]
